project_setup:
  project_name: "Telco-Churn-MLOps"
  experiment_name: "initial-baseline"

data_params:
  raw_path: "data/telco_churn.csv"
  test_size: 0.2
  random_state: 42

model_params:
  n_estimators: 100
  max_depth: 5
  learning_rate: 0.1