project_setup:
  project_name: "Telco-Churn-MLOps"
  experiment_name: "xgboost-feature-eng-v4"
  model_type: "xgboost"

data_params:
  raw_path: "data/telco_churn_v2.csv"
  test_size: 0.2
  random_state: 42

model_params:
  logistic_regression:
    max_iter: 1000
    solver: "lbfgs"
  
  # üèÜ BEST PARAMETERS from your RandomizedSearchCV
  xgboost:
    n_estimators: 100
    max_depth: 3
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    use_label_encoder: False
    eval_metric: "logloss"
    random_state: 42
