_wandb:
    value:
        cli_version: 0.24.0
        e:
            9iz1h9lz5rdcns1edmbuvxabww67fdyq:
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "155278327808"
                        used: "121183731712"
                email: m.riad@esi-sba.dz
                executable: /home/moha/miniconda3/bin/python
                git:
                    commit: 817e21bf0d1b4a86a34096164bd45f078f5ea4b5
                    remote: https://Mohariade:@github.com/Mohariade/Telco-Customer-Churn-MLOPs.git
                host: moha-Latitude-5300
                memory:
                    total: "8090021888"
                os: Linux-5.15.0-131-generic-x86_64-with-glibc2.35
                program: -m src.train
                python: CPython 3.13.5
                root: /home/moha/SEDC/MLOPS_project
                startedAt: "2026-01-30T14:45:47.199996Z"
                writerId: 9iz1h9lz5rdcns1edmbuvxabww67fdyq
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 5
                - 6
                - 53
                - 105
            "2":
                - 5
                - 6
                - 53
                - 105
            "3":
                - 2
                - 16
            "4": 3.13.5
            "5": 0.24.0
            "8":
                - 2
            "12": 0.24.0
            "13": linux-x86_64
data_params:
    value:
        random_state: 42
        raw_path: data/telco_churn_v2.csv
        test_size: 0.2
model_params:
    value:
        logistic_regression:
            max_iter: 1000
            solver: lbfgs
        xgboost:
            learning_rate: 0.05
            max_depth: 6
            n_estimators: 150
project_setup:
    value:
        experiment_name: xgboost-challenger-v2
        model_type: xgboost
        project_name: Telco-Churn-MLOps
